version: 0.2

phases:
  install:
    commands:
      - pip install jinja2 pyyaml
  build:
    commands:
      - python app.py
      - python render.py
      - aws cloudformation deploy
          --template-file pipeline.yml
          --stack-name hello-world-pipeline-stack
          --capabilities CAPABILITY_NAMED_IAM